/* ============ בחינות אמי"ר הרשמיות — תוכן בלבד ============
   נוצר אוטומטית על ידי build-exams.js מתוך חוברת ההדרכה של המרכז הארצי
   (nite.org.il/files/amir/amir_guide.pdf — מופצת בחינם לתרגול נבחנים).
   ⛔ לא לערוך ביד — להריץ מחדש את build-exams.js.

   o[0] = התשובה הנכונה תמיד (כמו בכל בנקי השאלות בפרויקט); הערבוב בתצוגה.
   verified:true = הבחינה אומתה מול השאלות שששון כבר פתר ואושרו ידנית.
   ⚠️ verified:false לא נטען למערכת — ראה OFF ב-index.html. */
'use strict';
const OFFICIAL={
 "1AM":{verified:true,
  sc:[
  {s:"All doctors – not only dentists – should have basic knowledge of the teeth and how they are by disease.",
   o:["affected","formed","corrected","explained"],src:"1AM/1/1",noBlank:true},
  {s:"The judge refused to ___ the evidence to be presented in court, stating that it was not relevant to the case.",
   o:["allow","pardon","silence","restrict"],src:"1AM/1/2"},
  {s:"James Young, a Scottish chemist, died a wealthy man, having amassed a great ___ by successfully marketing paraffin lighting oil.",
   o:["fortune","file","crowd","laboratory"],src:"1AM/1/3"},
  {s:"Among women, cancer of the colon is the second most ___ type of cancer after breast",
   o:["common","recent","definite","available cancer."],src:"1AM/1/4"},
  {s:"One of the impressive ___ of ancient monuments is their extraordinary size.",
   o:["characteristics","satisfactions","arguments","limitations"],src:"1AM/1/5"},
  {s:"it is known when gunpowder was first used in warfare, it is not known when it was invented.",
   o:["While","Since","Before","Whenever"],src:"1AM/1/6",noBlank:true},
  {s:"Punctuation marks are used to ___ the meaning of written language.",
   o:["clarify","originate","translate","distribute"],src:"1AM/1/7"},
  {s:"What may be the oldest piece of art in existence is ___ at the Israel Museum.",
   o:["on display","on account","in command","in effect"],src:"1AM/1/8"},
  {s:"exposure to harmful substances in the air may cause permanent damage to the lungs.",
   o:["Prolonged","Synthetic","Appropriate","Classified"],src:"1AM/1/9",noBlank:true},
  {s:"International banks are occasionally forced to close some of their branches because of political in host countries.",
   o:["unrest","modesty","identities","appearances"],src:"1AM/1/10",noBlank:true},
  {s:"The marble carvings on the Ludovisi sarcophagus ___ a Roman battle scene.",
   o:["depict","eliminate","resent","restrain"],src:"1AM/1/11"},
  {s:"If one is planning a trip, a travel agent may be helpful in arranging transportation and hotel.",
   o:["reservations","publications","conversations","observations"],src:"1AM/2/1",noBlank:true},
  {s:"Unfortunately, newspaper reporters sometimes use their own ___ if they cannot get",
   o:["imaginations","expectations","organization","attention facts for their stories."],src:"1AM/2/2"},
  {s:"Providing better education for their citizens may be the ___ economic success for",
   o:["key to","exception to","risk of","compensation for many countries in the next century."],src:"1AM/2/3"},
  {s:"The principal ___ of water for ancient Jerusalem was the spring of Gihon, located on the slopes of Mount Zion.",
   o:["source","release","exchange","property"],src:"1AM/2/4"},
  {s:"Doctors know they cannot save all patients as some are ___ help.",
   o:["beyond","after","less","no"],src:"1AM/2/5"},
  {s:"The first British steamship to be built ___ of iron was the Aaron Manby.",
   o:["entirely","relatively","frequently","rapidly"],src:"1AM/2/6"},
  {s:"As jungles and savannas ___ due to destructive acts perpetrated by humans, the number of animals in them dwindles.",
   o:["shrink","resume","coincide","improvise"],src:"1AM/2/7"},
  {s:"Some people think the differences in cognitive ability between men and women are genetically determined, while others believe they are the result of.",
   o:["upbringing","underachievement","downfall","oversight"],src:"1AM/2/8",noBlank:true},
  {s:"Like Kandinsky and Chagall, the sculptor Pevsner left Russia after the Soviet regime its disapproval of modern art.",
   o:["voiced","traded","repaired","secured"],src:"1AM/2/9",noBlank:true},
  {s:"Given the current government's tyrannical domestic policies, the chances of political reform in Cuba seem.",
   o:["remote","rebellious","strict","sincere"],src:"1AM/2/10",noBlank:true},
  {s:"Since photography has become so complex, people who work in the field must have understanding of photographic technique.",
   o:["a thorough","an overlooked","an intrusive","a random"],src:"1AM/2/11",noBlank:true},
  {s:"The ___ weather in Amsterdam often turns the water in the city's canals to ice.",
   o:["freezing","mixed","frequent","constant"],src:"1AM/3/1"},
  {s:"The racing of Thoroughbred horses was once exclusively the sport of kings, but today it is also enjoyed by citizens.",
   o:["ordinary","liberal","friendly","attractive"],src:"1AM/3/2",noBlank:true},
  {s:"Though Gertrude Stein died more than five decades ago, only now is her work finally winning the that other writers believe it deserves.",
   o:["recognition","satisfaction","performance","significance"],src:"1AM/3/3",noBlank:true},
  {s:"As the economy fails, the people's support for the president seems to be.",
   o:["declining","flowing","spreading","settling"],src:"1AM/3/4",noBlank:true},
  {s:"The discovery of antibiotics such as penicillin is ___ the great landmarks in modern medicine.",
   o:["among","beyond","over","across"],src:"1AM/3/5"},
  {s:"A child's sense of self begins to develop in infancy, but cannot be considered fully until the child is much older.",
   o:["formed","copied","replaced","approved"],src:"1AM/3/6",noBlank:true},
  {s:"Particularly at the beginning of their college years, students may worry ___ about whether they will succeed.",
   o:["excessively","sensitively","intelligently","productively"],src:"1AM/3/7"},
  {s:"The Russian government's ___ on the sale of vodka resulted in a reduction in alcohol consumption.",
   o:["ban","risk","claim","loan"],src:"1AM/3/8"},
  {s:"For some people, switching from depression to high spirits may be ___ a matter of getting a daily dose of sunlight.",
   o:["merely","accurately","unfortunately","originally"],src:"1AM/3/9"},
  {s:"In order to arouse potential readers' interest in a book, a reviewer's ___ must be both informative and entertaining.",
   o:["critique","retreat","dilemma","enclosure"],src:"1AM/3/10"},
  {s:"Due to an unexpected increase in exports, the French Ministry of Finance has had to its original estimates of economic growth for the year.",
   o:["revise","imply","prescribe","deduce"],src:"1AM/3/11",noBlank:true}],
  rs:[
  {s:"Most people want more than they can afford to buy.",
   o:["Most people do not have enough money to buy everything they want.","Most people can afford to buy more than they really need.","In order to buy the things they want, people need money.","People buy many things, but cannot pay for all of them."],src:"1AM/1/12"},
  {s:"The rise in popularity of the English novel was largely due to the success of two nineteenth-century novelists: Dickens and Hardy.",
   o:["It was mostly because of Dickens and Hardy, two writers in the nineteenth century, that the English novel gained popularity.","Two nineteenth-century English authors, Dickens and Hardy, were successful at writing novels only because of their popularity.","During the nineteenth century, two English novelists, Dickens and Hardy, gained popularity because of their novels.","The rising success of the English novel helped increase the popularity of two nineteenth-century writers: Dickens and Hardy."],src:"1AM/1/13"},
  {s:"Throughout history there have been many different notions about which types of behaviour constitute insanity.",
   o:["There have always been different ideas about what can be considered insane behaviour.","Different types of insanity have always been a part of people's behaviour.","Throughout history, certain types of behaviour have always been considered insane.","People have a long history of insanity, which has not always been well understood."],src:"1AM/1/14"},
  {s:"Whether people's appreciation of beauty is innate or acquired is a question addressed in Plato's philosophical works.",
   o:["In his philosophical writings Plato considered this question: Are people born with an appreciation of beauty or do they acquire it?","People asked Plato to answer the following philosophical question: Do we have a real desire for beauty or is it only imagined?","Why do people have a need for beauty? The answer to this question may be found by reading Plato's works.","What is one of the issues discussed in Plato's philosophical writings? How people learn to appreciate beauty."],src:"1AM/1/15"},
  {s:"Aside from providing one's children with love, many responsibilities accompany parenting.",
   o:["Being a parent involves many responsibilities in addition to loving one's children.","People who become parents learn to love and take responsibility for their children.","One of the responsibilities of parents is loving their children.","Not all responsible parents provide their children with love."],src:"1AM/1/16"},
  {s:"Many scientific discoveries are attributed to famous scientists who, in the majority of cases, merely completed a process that was already developing, and which, sooner or later, would have been completed by others.",
   o:["People often credit famous scientists, who in most cases were only completing a process already begun, with discoveries that would eventually have been made by others.","In the majority of cases, even famous scientists attribute their discoveries to processes that were begun, but not necessarily completed, by others.","Sooner or later, the discoveries made by famous scientists are recognized as being the result of a long process of development usually begun, and sometimes even completed, by others.","In most cases, scientists become famous for making a particular discovery, rather than for completing work on processes that were begun and developed by others."],src:"1AM/1/17"},
  {s:"The greatest favour the emperor Augustus did for Rome was to give it peace.",
   o:["Giving the Romans peace was the best thing Augustus did for them.","Augustus was the favourite emperor at the time Rome was at peace.","The Romans favoured Augustus because he acted peacefully.","Augustus was Rome's greatest emperor because he made peace."],src:"1AM/2/12"},
  {s:"Most of Frank Lloyd Wright's clients were awed by his brilliance.",
   o:["Wright's great intelligence impressed most of his clients.","Wright's clients were mainly bright and impressive.","Wright was smarter than most of his clients thought he was.","Wright lost many clients even though he was talented."],src:"1AM/2/13"},
  {s:"As a result of its extreme rarity and secretive nature, very little is known about the behavior of the snow leopard.",
   o:["We do not know much about the behavior of snow leopards because they are secretive and there are so few of them.","Since they behave so secretively, it is not known how many snow leopards still exist.","Most of the secret behavior of the extremely rare snow leopard has yet to be studied.","Although the snow leopard is not a rare animal, it is not commonly studied because of its highly secretive behavior."],src:"1AM/2/14"},
  {s:"Whales rank high among the world's endangered species and many international agreements have been made to conserve them.",
   o:["A great number of international agreements have been made to protect one of the world's most endangered species – the whale.","The whale is just one of the many endangered species that should be protected by international agreements.","There is international agreement that certain endangered species, such as the whale, should be protected.","An international agreement has been made which includes whales on the list of endangered species requiring protection."],src:"1AM/2/15"},
  {s:"The 200-year-old Constitution of the United States is still relevant today because it is constantly being reinterpreted in light of evolving attitudes and behavior.",
   o:["Since the way the American Constitution is understood is constantly being changed in accordance with evolving attitudes and behavior, it still has relevance even after 200 years.","After 200 years, the continually evolving attitudes and behavior of the American people are beginning to influence the way the United States Constitution is interpreted.","The people of the United States are constantly studying their 200-year-old Constitution in order to interpret the effect it has had on changing attitudes and behavior.","The American Constitution, which is two hundred years old, will only continue to have relevance if the people of the United States constantly reinterpret their behavior and attitudes."],src:"1AM/2/16"},
  {s:"At the outbreak of World War I, there were very few aeroplanes in existence and their military role was far from clear.",
   o:["No one was sure how the small number of aeroplanes available at the beginning of World War I would be used by the military.","From the start of World War I, the few aeroplanes that were in use had a specific military role.","Because the number of aeroplanes available to the military was small, they were not used during World War I.","No one knew how many aeroplanes would be used by the military in World War I or what their role would be."],src:"1AM/2/17"},
  {s:"Many nations are involved in improving public education.",
   o:["Improving public education is something many nations are working towards.","Nations should work together on the issue of public education.","The purpose of public education is to improve the nation.","Public education is necessary for the improvement of many nations."],src:"1AM/3/12"},
  {s:"All the articles sold at the auction were of superior quality, but only a few were actually antiques.",
   o:["Not many real antiques could be found among the items sold at the auction, although all of them were of high quality.","Because the quality of the articles sold at the auction was so high, it was expected that they would be antiques.","Superior-quality antiques were not actually found among the articles sold at the auction.","Some articles of high quality were sold at the auction, and all of them were truly antiques."],src:"1AM/3/13"},
  {s:"While other modern artists tried to discourage associations between their works and literary or historical subjects, Picasso encouraged such associations.",
   o:["Picasso, unlike other modern artists, encouraged people to associate his work with subjects from literature or history.","The fact that Picasso encouraged associations between his work and literary and historical themes was discouraging to other modern artists.","The subjects from literature and history that Picasso chose to represent in his works were difficult to associate with the subjects chosen by other artists.","Picasso encouraged other modern artists to make connections between their art and literary or historical subjects."],src:"1AM/3/14"},
  {s:"Prolonged pain diminishes one's enjoyment of life.",
   o:["Pain suffered over a long period of time makes life less enjoyable.","Living without pain does not necessarily make life enjoyable.","When our lives are full of joy, we do not experience pain.","Nothing lessens one's enjoyment of life more than pain."],src:"1AM/3/15"},
  {s:"In the 16th and 17th centuries, the agonizing problem for Christians was less one of coexistence with followers of other religions than one of coexistence with fellow Christians of different denominations.",
   o:["Christians of different denominations in the 16th and 17th centuries found it more difficult to live with each other than with followers of other religions.","It was extremely difficult for non-Christians in the 16th and 17th centuries to coexist with Christians, regardless of their denomination.","One of the biggest problems for Christians in the 16th and 17th centuries was the fact that they had to live with non-Christians of various denominations.","The existence of several Christian denominations in the 16th and 17th centuries made Christianity more problematic than other religions of that time."],src:"1AM/3/16"},
  {s:"No summary can impart the wealth of allusions to the characters and situations in James Joyce's works provided by Richard Ellman in James Joyce – a biography of the famous author.",
   o:["Richard Ellman includes so many allusions to characters and situations from Joyce's works in his biography James Joyce that they cannot be conveyed in a summary.","In James Joyce – a biography of the famous author – Richard Ellman summarizes the allusions used by Joyce to refer to characters and situations in his works.","James Joyce, a biography written by Richard Ellman, includes many comprehensive quotations taken from descriptions of characters or situations in the famous author's works.","The richness of James Joyce's writing is alluded to by Richard Ellman in his biography James Joyce through descriptions of characters and situations in the famous author's works."],src:"1AM/3/17"}]},
 "2AM":{verified:false,
  sc:[
  {s:"The history of South America is usually divided into three main ___: the pre- Columbian, the colonial, and the modern.",
   o:["periods","grades","activities","programs"],src:"2AM/1/1"},
  {s:"The United States absorbs more immigrants than all other industrialized combined.",
   o:["nations","actions","systems","forces"],src:"2AM/1/2",noBlank:true},
  {s:"Darwin's visit to the Galápagos Islands led him to formulate his ___ of evolution.",
   o:["theory","invention","expectation","subject"],src:"2AM/1/3"},
  {s:"The main ___ facing the international community is that of creating a broader understanding among peoples and governments.",
   o:["challenge","region","figure","symptom"],src:"2AM/1/4"},
  {s:"Since World War II, Italy has had no ___ than 52 governments.",
   o:["fewer","sooner","closer","better"],src:"2AM/1/5"},
  {s:"As the techniques used in photography become more ___, it takes photographers longer to master the craft.",
   o:["sophisticated","entertaining","universal","obvious"],src:"2AM/1/6"},
  {s:"Many patients are used to accepting their doctors' opinions ___, rarely questioning their diagnoses.",
   o:["uncritically","intentionally","curiously","honestly"],src:"2AM/1/7"},
  {s:"In 1964, the United States bombed North Vietnamese bases in ___ attacks on",
   o:["retaliation for","collaboration with","deference to","reliance upon American naval destroyers."],src:"2AM/1/8"},
  {s:"The use of solar energy for everyday purposes is a ___ recent development.",
   o:["surprisingly","formerly","distantly","constantly"],src:"2AM/1/9"},
  {s:"To ___ their country's financial predicament and impress both allies and enemies, government officials purchased much expensive military equipment.",
   o:["conceal","estimate","inspect","release"],src:"2AM/1/10"},
  {s:"The introduction of unusual sounds into traditional musical forms was a ___ feature of 20th-century music.",
   o:["prominent","dignified","stabilizing","resourceful"],src:"2AM/1/11"},
  {s:"Scientists are finding it difficult to ___ when, where and – perhaps most importantly – how life on earth began.",
   o:["agree on","argue with","arrange for","adapt to"],src:"2AM/2/1"},
  {s:"Swedish automobiles are ___ their dependability.",
   o:["known for","pleased with","driven to","rejected by"],src:"2AM/2/2"},
  {s:"The ideal witness to a ___ is one who was able to get a good look at the thief.",
   o:["robbery","tragedy","competition","marriage"],src:"2AM/2/3"},
  {s:"The more comfortable one feels in the water, the ___ it is to concentrate on swimming lessons.",
   o:["easier","better","weaker","stranger"],src:"2AM/2/4"},
  {s:"The writings of the Yugoslavian author Ivo Andric on the plight of beggars and other needy people reveal his sensitivity and.",
   o:["compassion","confinement","flattery","abstraction"],src:"2AM/2/5",noBlank:true},
  {s:"Because Cyprus is strategically in the northeast corner of the Mediterranean, it has always been coveted by more powerful countries.",
   o:["situated","reduced","warned","defined"],src:"2AM/2/6",noBlank:true},
  {s:"The scientist Galileo was a central ___ in Europe's transition from the Dark Ages to modern times.",
   o:["figure","method","creation","concept"],src:"2AM/2/7"},
  {s:"The increase in the number of cases of lung cancer in the past twenty years has great concern all over the world.",
   o:["aroused","avoided","disturbed","declared"],src:"2AM/2/8",noBlank:true},
  {s:"The noise of airplanes taking off and landing not only raises the blood pressure of children in schools near airfields, but may also their reasoning ability.",
   o:["impair","duplicate","signify","confess"],src:"2AM/2/9",noBlank:true},
  {s:"Heartbeats are ___ muscle movements; they cannot be controlled consciously.",
   o:["involuntary","inconsiderate","improbable","impractical"],src:"2AM/2/10"},
  {s:"The narcotics market flourishes not only because of police ineptitude, but also because of the of politicians.",
   o:["indifference","implication","rudeness","stability"],src:"2AM/2/11",noBlank:true},
  {s:"Gunpowder, which was ___ used in China in the eighth century, did not become well known in Europe until the middle of the thirteenth century.",
   o:["first","even","next","usually"],src:"2AM/3/1"},
  {s:"Delays in the development of new social services and educational policies have strikes and unrest in Italy.",
   o:["led to","stayed with","sent for","hoped for"],src:"2AM/3/2",noBlank:true},
  {s:"Anne Frank achieved immortality as a Jewish heroine ___ her poignantly evocative diary.",
   o:["through","beside","during","between"],src:"2AM/3/3"},
  {s:"Daniel Boone, an American pioneer, was one of the first to brave the dangers of the wilderness of Kentucky.",
   o:["unexplored","reliable","unsatisfied","available"],src:"2AM/3/4",noBlank:true},
  {s:"Hunger is a sense of ___ experienced in the area of the stomach, and may actually be painful.",
   o:["discomfort","force","inequality","expansion"],src:"2AM/3/5"},
  {s:"Despite a lack of information about racial segregation in Canada, the fact that the phenomenon exists cannot be.",
   o:["doubted","considered","assisted","suspected"],src:"2AM/3/6",noBlank:true},
  {s:"The twelve leading nations of Western Europe have launched a bold plan to reinvigorate the European Community by forming a single economy.",
   o:["integrated","displaced","irregular","sociable"],src:"2AM/3/7",noBlank:true},
  {s:"In the 18th century, the Swedish botanist Linnaeus ___ a system for classifying all known plants and animals according to genus and species.",
   o:["devised","deceived","annoyed","exaggerated"],src:"2AM/3/8"},
  {s:"Hurricanes are violent storms that develop in the tropics and are ___ by high-speed winds.",
   o:["characterised","analysed","implied","guaranteed"],src:"2AM/3/9"},
  {s:"The ___ at Hull House in Chicago include a day nursery, a gymnasium and a community kitchen.",
   o:["facilities","reinforcements","appliances","treasures"],src:"2AM/3/10"},
  {s:"If an election were held today, the president would win by a very wide.",
   o:["margin","survey","convention","notion"],src:"2AM/3/11",noBlank:true}],
  rs:[
  {s:"In 1972, India was home to 500 million people – fifteen percent of the world's population.",
   o:["Fifteen percent of the world's population – 500 million people – lived in India in 1972.","In 1972, the world's population was 500 million people, fifteen percent of whom were Indian.","India's population increased by fifteen percent in 1972, raising the number of people living there to 500 million.","Since 1972 the population of India – fifteen percent of the world's population – has increased by 500 million people."],src:"2AM/1/12"},
  {s:"Of all the arts, none is more physically demanding than dance.",
   o:["Dance requires more physical effort than the other arts.","Good physical condition is no longer demanded for dance.","Dance is more physically than artistically demanding.","Dancers in good physical condition can do more than artists."],src:"2AM/1/13"},
  {s:"The Far East is playing an increasingly important role in our world today, and for this reason we ought to know something of its past.",
   o:["We should learn about the history of the Far East because of the area's growing global importance today.","In the Far East, knowing about the past is more important than learning about the world today.","It is becoming more important that the history of the Far East play a role in our world today.","The history of the Far East is only one of the reasons for the area's growing global importance today."],src:"2AM/1/14"},
  {s:"The lyrics of Stephen Sondheim, so perfectly constructed that they seem to rhyme by accident, reveal his astounding facility for language.",
   o:["So well constructed that their rhyming appears to be accidental, Sondheim's lyrics reflect his amazing aptitude for language.","Although they reveal his mastery of language and are so well constructed, Sondheim's lyrics do not always rhyme.","The construction of perfect rhymes in his lyrics is only one part of Sondheim's amazing work with language.","That Sondheim was able to demonstrate his great language abilities through the amazing rhymes in his lyrics is not accidental."],src:"2AM/1/15"},
  {s:"However prestigious the awards and however admired the winners, the announcement of the recipients of book prizes is inevitably greeted with derision by some people.",
   o:["There are always some scornful reactions to the announcement of the winners of book prizes, no matter how highly the awards and those who receive them are regarded.","People generally show interest in the winners of book prizes when they are announced, even if the awards are not substantial and the recipients are not admired.","Inevitably, those who have been announced as the winners of book prizes look forward to receiving them, especially if the awards are considered prestigious by most people.","The derision which accompanies the announcement of the winners of book prizes is a result of the fact that many awards and recipients are not held in high esteem."],src:"2AM/1/16"},
  {s:"Precisely how endangered species around the world should be protected has not yet been determined, judging from the near absence of specific measures advanced by environmental experts.",
   o:["It may be assumed that since very few definite suggestions on how to protect endangered species have been proposed by environmental experts, specific methods of protection have not yet been decided upon.","In order to judge what various experts on the environment have done to protect endangered species, we need to examine the specific measures they have proposed for dealing with the problem.","It is not enough for experts concerned with the environment to talk about the need for protecting endangered species; they must also suggest specific ways of doing so.","The more environmental experts know, the better they will be able to judge what the best methods are for protecting the world's endangered species."],src:"2AM/1/17"},
  {s:"The Dead Sea, which at 425 meters below sea level is the lowest spot on earth, is a major source of minerals.",
   o:["Many minerals are found in the Dead Sea, the lowest place on earth.","The Dead Sea is the only low place in the world where minerals are found.","Since the Dead Sea is below sea level, it is the source of many minerals.","There are many minerals 425 meters below the level of the Dead Sea."],src:"2AM/2/12"},
  {s:"Some psychologists now prescribe jogging for their patients, as research indicates that exercise can cure depression.",
   o:["Since research shows that depression can be cured by exercise, some psychologists now advise their patients to jog.","Some psychologists have researched jogging as a possible cure for their patients' depression.","Joggers were the subjects of a psychological study which showed that exercise should be prescribed to cure depression.","Patients who want to prevent depression should begin to jog, since studies show that exercise affects us psychologically."],src:"2AM/2/13"},
  {s:"Spider silk is remarkably strong, and scientists are endeavouring to create other materials which have this quality.",
   o:["Scientists are trying to produce materials with a strength equal to that of spider silk.","Spider silk is being used by scientists in order to produce other, stronger materials.","If scientists can reproduce spider silk, they can create other materials with similar qualities.","Materials which have the quality of being stronger than spider silk are being created by scientists."],src:"2AM/2/14"},
  {s:"To understand the Russian attitude towards education, one must realize that scholars there enjoy much greater prestige than those in Britain or the United States.",
   o:["Knowing that being a scholar is much more prestigious in Russia than in Britain or the United States is necessary for understanding what Russians think about education.","One reason for the great prestige enjoyed by Russian scholars is that they are more involved in education than are scholars in Britain or the United States.","British and American scholars are often unaware that their attitudes toward education make their positions much less prestigious than the positions of Russian scholars.","British and American scholars realize that they are different from Russian scholars because they enjoy less prestige and have different attitudes towards education."],src:"2AM/2/15"},
  {s:"After the Spanish conquistador Francisco Pizarro invaded Peru in 1532, European technology rapidly supplanted the indigenous metallurgical methods of northern Peru.",
   o:["Northern Peru's native metal-making methods were quickly replaced by European technology following Pizarro's invasion of Peru in 1532.","The traditional metal weapons of northern Peru proved inadequate against the technologically advanced ones of Pizarro, who invaded Peru in 1532.","After Pizarro invaded Peru in 1532, he discovered that much of European technology was based on old metal-making methods native to northern Peru.","In 1532, using technologically superior European weapons, Pizarro invaded Peru and stole traditional metal objects from the northern part of the country."],src:"2AM/2/16"},
  {s:"Over the last ten years, the expenditure on research by French companies has increased annually by more than five percent.",
   o:["French companies have increased the amount of money they spend on research by over five percent each year during the past decade.","In the past ten years there has been an annual increase of over five percent in the number of French companies investing in research.","Every year for the past ten years, French companies have spent at least five percent of their total expenditure on research.","The French companies which have invested money in research over the past decade have increased their profits by more than five percent."],src:"2AM/2/17"},
  {s:"When a person suffers a stroke, physicians are unable to limit the extent of the damage it causes, no matter how quickly they reach him.",
   o:["Even if doctors reach a stroke victim quickly, they cannot control the amount of damage caused by the stroke.","In order to prevent strokes from causing damage, physicians must reach stroke victims as quickly as possible.","If people who suffer strokes are able to contact their doctors quickly, the resulting damage will be limited.","No matter how serious the damage caused by a stroke, physicians can treat it if the victim calls them quickly."],src:"2AM/3/12"},
  {s:"For three thousand years, China existed in self-imposed isolation.",
   o:["China kept itself isolated for three thousand years.","After three thousand years, China imposed a state of solitude on itself.","China existed for three thousand years due to its self-imposed isolation.","China escaped from its solitude after three thousand years."],src:"2AM/3/13"},
  {s:"One of the most long-standing and hotly debated issues in philosophy and psychology is whether nature or nurture exerts more influence in shaping the mind.",
   o:["Which affects the mind's development more: nature or nurture? That is a question that philosophers as well as psychologists have been arguing about for a long time.","How can psychologists and philosophers understand the human mind better? One thing they must study and discuss is the issue of nature and nurture.","What kind of influence does human development have on nature and nurture? Psychologically and philosophically that is a very difficult question to answer.","Why are there such serious debates in philosophy and psychology? Because no one knows whether nature or nurture is more important to the mind's development."],src:"2AM/3/14"},
  {s:"Dubin's claim that \"all biography is ultimately fiction\" is one with which most contemporary theorists of literature would concur.",
   o:["Most modern literary theorists would agree with Dubin's statement that biography is actually fiction.","Dubin's ideas about biographical fiction are based on those of other modern literary theorists.","Theorists of literature once criticized Dubin's claim about the relationship between biography and fiction.","Contemporary literary criticism is full of claims like Dubin's about the ultimate aim of biographers."],src:"2AM/3/15"},
  {s:"If South Africa's land were more suited to agriculture, three centuries of winemaking might have produced a grand tradition there.",
   o:["Three hundred years of producing wine might have led to a grand winemaking tradition in South Africa had agricultural conditions there been more favorable.","Although winemaking has not been a grand tradition in lands with unfavorable agricultural conditions, in South Africa it has been successful for three hundred years.","In South Africa, winemaking has only been a grand tradition for three centuries, while in places with better agricultural conditions, the tradition is much older.","In countries with favorable agricultural conditions, such as those in South Africa, a grand tradition of winemaking may develop in less than three centuries."],src:"2AM/3/16"},
  {s:"Experiments conducted by the physicist Ernest Rutherford in 1899 revealed that radioactive substances emit more than one kind of ray.",
   o:["That different types of rays are emitted by radioactive substances was shown in experiments which physicist Ernest Rutherford conducted in 1899.","In 1899, physicist Ernest Rutherford conducted experiments which showed how to remove different types of rays from radioactive substances.","The physicist Ernest Rutherford conducted experiments in 1899 in order to create radioactive substances that would emit different types of rays.","Experiments which showed that radioactive rays affect different types of substances were conducted in 1899 by Ernest Rutherford, a physicist."],src:"2AM/3/17"}]},
 "3AM":{verified:false,
  sc:[
  {s:"The city of Cordoba in Spain was once a ___ of intellectual and academic activity.",
   o:["center","measure","chapter","season"],src:"3AM/1/1"},
  {s:"Although it has been illegal to ___ bald eagles in the United States since 1940, there are only a few of these birds left in the country.",
   o:["hunt","watch","find","fly"],src:"3AM/1/2"},
  {s:"All parents should provide a ___ and balanced diet for their children.",
   o:["healthy","separate","potential","straight"],src:"3AM/1/3"},
  {s:"In the late 1960s, U.S. Army scientists realized that ___ spider silk is both extremely strong and highly elastic, it can be used to make bullet-proof vests.",
   o:["because","unless","before","until"],src:"3AM/1/4"},
  {s:"The government's plan to modify the tax system was never very grand in scale; it involved only changes.",
   o:["minor","constant","recent","complex"],src:"3AM/1/5",noBlank:true},
  {s:"Even today, after so many years of ___, the continent of Antarctica still holds many mysteries.",
   o:["exploration","unawareness","approval","reform"],src:"3AM/1/6"},
  {s:"Recent polls in Britain have shown that public morale is low as a result of widespread government policies.",
   o:["disenchantment with","discrimination against","communion with","certification of"],src:"3AM/1/7",noBlank:true},
  {s:"Scientists have only begun to ___ the damage caused by human encroachment on the habitats of various animals.",
   o:["assess","enrage","obey","extract"],src:"3AM/1/8"},
  {s:"Compared to other great artists, Leonardo da Vinci completed ___ few paintings.",
   o:["relatively","favourably","regularly","permanently"],src:"3AM/1/9"},
  {s:"Hotel owners in New York City reached a tentative agreement with their employees, thus the strike threatened by the workers' union.",
   o:["averting","condemning","amassing","invoking"],src:"3AM/1/10",noBlank:true},
  {s:"The researchers published a lengthy report describing all of their findings in detail, as well as a shorter, more version.",
   o:["concise","absorbent","secular","morose"],src:"3AM/1/11",noBlank:true},
  {s:"Two billion people – 70 percent of the ___ of all developing countries – live without the benefit of electricity.",
   o:["population","culture","condition","statistic"],src:"3AM/2/1"},
  {s:"the police had threatened to arrest all the demonstrators, they failed to do so.",
   o:["Although","Since","When","Before"],src:"3AM/2/2",noBlank:true},
  {s:"Aircraft technology has progressed so ___ that a ten-year-old plane is considered an antique.",
   o:["rapidly","partially","carelessly","narrowly"],src:"3AM/2/3"},
  {s:"If people ate nutritionally balanced meals every day, they would have ___ health problems.",
   o:["fewer","several","regular","similar"],src:"3AM/2/4"},
  {s:"Pottery making ___ an advanced stage of development very early in the history of civilization.",
   o:["reached","attempted","contacted","designed"],src:"3AM/2/5"},
  {s:"Linguists make a basic ___ among letters, classifying them as either vowels or consonants.",
   o:["distinction","interruption","concentration","assumption"],src:"3AM/2/6"},
  {s:"Due to a shortage of many goods, a black market – where goods are sold illegally – is in the former Soviet Union.",
   o:["flourishing","colliding","mediating","confessing"],src:"3AM/2/7",noBlank:true},
  {s:"The invention of movable type is ___ a Chinese printer named Bi Sheng who lived during the 11th century.",
   o:["attributed to","resented by","contained in","rotated by"],src:"3AM/2/8"},
  {s:"By 1150 B.C.E., many of the small, scattered villages of the Olmec people had into larger communities.",
   o:["merged","stumbled","deteriorated","lapsed"],src:"3AM/2/9",noBlank:true},
  {s:"In theory, modern management techniques are hard to fault, but in practice they have proven to be.",
   o:["disastrous","conscious","anxious","generous"],src:"3AM/2/10",noBlank:true},
  {s:"The Bronx Zoo, which opened in 1899, was the first zoo to provide spacious ___ for large groups of animals.",
   o:["enclosures","commentaries","destinies","adversaries"],src:"3AM/2/11"},
  {s:"As the world's human population keeps, the natural habitats of wild animals continue to be destroyed to make way for houses, factories and highways.",
   o:["growing","turning","resting","learning"],src:"3AM/3/1",noBlank:true},
  {s:"On the whole, the ancient Greeks were a patriarchal people; only in the city-state of Sparta did women hold of power.",
   o:["positions","deliveries","responses","efforts"],src:"3AM/3/2",noBlank:true},
  {s:"Penguins lost the ___ to fly millions of years ago, after their wings evolved into flippers.",
   o:["ability","attempt","permission","pressure"],src:"3AM/3/3"},
  {s:"People are more likely to give money to a charitable cause when they are assured that even a dollar will help than when they are asked to a large sum.",
   o:["contribute","coordinate","demonstrate","disregard"],src:"3AM/3/4",noBlank:true},
  {s:"Abundant wildlife makes Pennsylvania's forests ___ areas for hunting.",
   o:["suitable","cautious","broad","extinct"],src:"3AM/3/5"},
  {s:"In 1898 the United States ___ the struggle between the Cuban people and their Spanish rulers.",
   o:["intervened in","pleaded with","reverted to","applied for"],src:"3AM/3/6"},
  {s:"With each successful, the Aztecs gained territory, slaves and economic resources.",
   o:["conquest","deliberation","inference","exhibition"],src:"3AM/3/7",noBlank:true},
  {s:"Although Francis Bacon advocated a scientific way of thinking, many superstitious and beliefs are expressed in his writings.",
   o:["unfounded","unconcerned","unforeseen","ungrateful"],src:"3AM/3/8",noBlank:true},
  {s:"With the help of scientific advisors, a committee is ___ Europe's twenty-year-old cosmetics regulations.",
   o:["updating","predicting","outdoing","donating"],src:"3AM/3/9"},
  {s:"The monuments of Karnak were ___ during the early, middle and late Neolithic periods.",
   o:["erected","oppressed","offended","expelled"],src:"3AM/3/10"},
  {s:"Despite the international ___ film director and screenwriter Louis Malle received, he never won an Academy Award.",
   o:["acclaim","humility","tension","impulse"],src:"3AM/3/11"}],
  rs:[
  {s:"People from different dialectal regions of China are unable to communicate with one another through speech, although they can do so through reading and writing.",
   o:["Chinese people who speak different dialects are able to communicate with each other only through written language.","Because China's regional dialects are no longer very different, people's ability to communicate has improved greatly.","Although there are many different dialectal regions in China, people still manage to communicate through speech.","There are so many different dialects of Chinese that even people who can speak to each other cannot read or write each other's dialect."],src:"3AM/1/12"},
  {s:"Even during wartime, civil law must be upheld, and those who violate it must be punished.",
   o:["People who disobey civil law should be punished, even during a war.","Punishing those who break the law is difficult, especially during a war.","While there are many violations of civil law during peacetime, they are more frequent during a war.","Because upholding the law is so important in wartime, those who disobey it are punished."],src:"3AM/1/13"},
  {s:"Tiberias lies some 200 meters below sea level, on the ruins of the biblical town of Hammat.",
   o:["Tiberias, built atop the ruins of the biblical town of Hammat, is about 200 meters below sea level.","The ruins of the biblical town of Hammat, which is situated near Tiberias, lie 200 meters underwater.","The biblical town of Hammat, after it was rebuilt 200 meters below sea level, was called Tiberias.","The ruins of the biblical town of Hammat lie about 200 meters above Tiberias."],src:"3AM/1/14"},
  {s:"Given its inevitability, the fact that old age is generally regarded as a time to be dreaded rather than eagerly anticipated is lamentable.",
   o:["Since old age cannot be avoided, it is sad that most people think of it as a time to be feared rather than looked forward to.","The fact that most people do not look forward to their old age is tragic, but it is difficult to change the way people feel about getting old.","People who do not realize that old age may be the most enjoyable time of their lives are afraid of getting old.","If people realized how enjoyable old age can be, they would not be so worried about getting old."],src:"3AM/1/15"},
  {s:"Unless a pathogen like the Ebola virus alters its mode of transmission, it is unlikely to proliferate outside its natural habitat.",
   o:["A pathogen like the Ebola virus will probably not multiply on a large scale in areas other than its natural habitat if it does not change the way in which it is transmitted.","Unless it has a mode of transmission which is similar to that of the Ebola virus, a pathogen will probably not proliferate outside its natural habitat.","If a pathogen like the Ebola virus is transmitted in the usual way, it will probably not remain in its natural habitat but will multiply rapidly in other areas.","The natural habitat of the Ebola virus is unlikely to change or expand unless the virus's mode of transmission becomes more like that of other pathogens."],src:"3AM/1/16"},
  {s:"Yugoslav leader Broz Tito, in addition to being the only ruler of a Communist country who seemed to enjoy genuine popularity, was also the only one who employed more than terror and propaganda to govern his country, although he certainly employed them as well.",
   o:["Tito was unique among leaders of Communist countries in two ways: first, people actually seemed to like him, and second, he did not use terror and propaganda alone to rule his country.","Although Tito established his rule in Yugoslavia by using terror and propaganda, he governed his country well and became more popular than other leaders of Communist countries.","Although leaders of other Communist countries warned Tito that he would not be able to rule effectively without using terror and propaganda, he decided to stop using them and, as a result, became more popular.","Tito became Yugoslavia's most popular leader by refusing to employ terror and propaganda; in doing so, he ignored the example of other Communist leaders, who used these methods to attain power."],src:"3AM/1/17"},
  {s:"Women were generally responsible for farming in ancient agricultural societies.",
   o:["In ancient agricultural societies, farming was usually the work of women.","In ancient agricultural societies, women were only allowed to farm.","The most responsible women in ancient agricultural societies were the women who farmed.","Women have always worked in farming, especially in ancient agricultural societies."],src:"3AM/2/12"},
  {s:"Henry David Thoreau died at forty-four, having published relatively little of what he had written.",
   o:["Much of what Thoreau had written had not been published by the time he died at the age of forty-four.","Because Thoreau died when he was only forty-four, he managed to write and publish very little.","Most of what was written about Thoreau was only published forty-four years after his death.","Thoreau died at the age of forty-four, never having seen any of his work published."],src:"3AM/2/13"},
  {s:"The Social Democratic Party in Austria has been part of the government for all but four of the past fifty years.",
   o:["Excluding only four years, the Social Democratic Party has been part of the Austrian government for the past fifty years.","Four years ago, the Social Democratic Party ended its fifty-year leadership of the Austrian government.","Although the Social Democratic Party was part of the government in Austria for fifty years, it was the biggest party for only four years.","The Social Democratic Party joined the Austrian government fifty years ago, but left after four years."],src:"3AM/2/14"},
  {s:"In the 1970s, Saudi Arabia's annual revenue from petroleum sales was more than twice the amount needed to pay for imports.",
   o:["In Saudi Arabia, the yearly revenue from petroleum sales during the 1970s was more than twice as much as the country needed to pay for its imports.","In the 1970s, Saudi Arabia needed twice the amount of revenue that it was earning from petroleum sales to pay for its imports.","In the 1970s, Saudi Arabia doubled the size of its imports but did not have sufficient revenue from petroleum sales to pay for them.","Saudi Arabia had been spending more than twice its annual revenue on imports until petroleum sales in the country began to increase in the 1970s."],src:"3AM/2/15"},
  {s:"Some Americans view their country's economy as immune to external influences.",
   o:["Some Americans think that no outside influences can affect the American economy.","Some Americans claim that their country's economy has only a small effect on the economies of other countries.","According to some people in America, domestic issues have little influence on their country's economy.","Some people in America believe that their country's economy should be more open to the outside world."],src:"3AM/2/16"},
  {s:"Britain's domination of India was greatly facilitated by the political and military disunity in the country.",
   o:["The fact that India was divided politically and militarily made Britain's domination of the country easier.","Britain's domination was responsible for the political and military disunity that weakened India.","India suffered more than any other country from the political and military problems caused by Britain's domination.","India only became independent politically and militarily after Britain's domination of the country ended."],src:"3AM/2/17"},
  {s:"Although it is mostly desert, Saudi Arabia is one of the richest countries in the world thanks to its oil deposits.",
   o:["Saudi Arabia's oil deposits have made the country very rich, even though most of its territory is desert.","Saudi Arabia became a rich country after a large number of oil deposits were found in its deserts.","Many countries in the world have oil deposits in their deserts, but Saudi Arabia is the richest of them.","Since its oil deposits have made it so rich, Saudi Arabia has been able to take advantage of its deserts."],src:"3AM/3/12"},
  {s:"In 1954 British philosopher Bertrand Russell suggested that a meeting of scientists be convened for the purpose of discussing nuclear disarmament.",
   o:["In 1954 Bertrand Russell proposed that scientists meet in order to discuss the subject of nuclear disarmament.","A group of scientists that met in 1954 invited Bertrand Russell to speak about nuclear disarmament.","Bertrand Russell presented his ideas to the scientists who convened in 1954 to discuss nuclear disarmament.","Scientists who held a meeting in 1954 to discuss nuclear disarmament adopted many of Bertrand Russell's suggestions."],src:"3AM/3/13"},
  {s:"Few would contest the claim that Frank Lloyd Wright was the greatest American architect of the twentieth century.",
   o:["Most people would agree that Frank Lloyd Wright was the greatest twentieth- century American architect.","Only a few people can claim to be as famous as Frank Lloyd Wright, the greatest American architect of the twentieth century.","Few have been able to compete with Frank Lloyd Wright for the title of greatest twentieth-century American architect.","Most people are familiar with the name of the greatest American architect of the twentieth century: Frank Lloyd Wright."],src:"3AM/3/14"},
  {s:"Clouds, water surfaces and land surfaces emit electromagnetic energy as infrared radiation, the intensity of which increases as the temperature rises.",
   o:["The higher the temperature, the more intense the electromagnetic energy in the form of infrared radiation emitted by clouds and by water and land surfaces.","The intensity of the electromagnetic energy, or infrared radiation, emitted by clouds and by water and land surfaces causes their temperatures to rise.","The infrared radiation emitted by clouds and by water and land surfaces when the temperature is high is more intense than their electromagnetic energy.","When the temperature is high, the intense electromagnetic energy emitted by clouds and by water and land surfaces turns into infrared radiation."],src:"3AM/3/15"},
  {s:"Columbus grossly underestimated the distance between Europe and Cathay prior to his initial voyage to the New World.",
   o:["Before he travelled to the New World for the first time, Columbus thought that Cathay was much closer to Europe than it actually was.","It was only after travelling to Cathay from Europe that Columbus realized how great the distance between them was.","Before he travelled the great distance from Europe to Cathay in the New World, Columbus had little idea of what to expect during the voyage.","It took Columbus less time to travel from Europe to Cathay than he had estimated it would take before his voyage began."],src:"3AM/3/16"},
  {s:"Many American writers and poets, disillusioned with their country's moral standards, became expatriates in the post-World War I period.",
   o:["In the period following World War I, many American writers and poets – disappointed with America's moral standards – left their country.","Although many American poets and writers were disappointed with the moral standards of their country after World War I, they remained patriots.","The subjects that America's writers and poets chose to write about reflected their belief that the country's moral standards had declined following World War I.","Many disillusioned American writers and poets chose to live abroad in the post- World War I period and consequently had less influence on their country's moral standards."],src:"3AM/3/17"}]},
 "4AM":{verified:true,
  sc:[
  {s:"Titanium is used in the manufacture of aircraft and jet engines because it is strong and light.",
   o:["both","yet","less","only"],src:"4AM/1/1",noBlank:true},
  {s:"The ___ \"to eat lotus,\" which was used by many ancient Chinese writers, means \"to forget.\"",
   o:["phrase","allowance","resource","debate"],src:"4AM/1/2"},
  {s:"The first democratic elections in Russia were conducted ___, despite fears of widespread violence.",
   o:["peacefully","additionally","thoughtlessly","affordably"],src:"4AM/1/3"},
  {s:"A solar battery ___ sunlight into electricity.",
   o:["converts","affirms","adores","carves"],src:"4AM/1/4"},
  {s:"Honduras, where the average ___ is less than $2,000 a year, is one of the poorest countries in the Western Hemisphere.",
   o:["income","errand","factor","burden"],src:"4AM/1/5"},
  {s:"A new ___ in space exploration began on October 4, 1957, when the first satellite, Sputnik, was launched by the Soviet Union.",
   o:["era","fund","lapse","core"],src:"4AM/1/6"},
  {s:"When King Richard I left England to fight in the Crusades, his brother John ruled the country in Richard's.",
   o:["absence","comparison","cushion","annoyance"],src:"4AM/1/7",noBlank:true},
  {s:"In Japanese cities, where living space is, the typical family lives in a two-room apartment, with everyone sleeping in the same room.",
   o:["scarce","broad","clumsy","mature"],src:"4AM/1/8",noBlank:true},
  {s:"Aspirin is an effective means of preventing dangerous blood clots;, it is inexpensive and has few side effects.",
   o:["moreover","nevertheless","however","therefore"],src:"4AM/1/9",noBlank:true},
  {s:"Each year, the United States Border Patrol ___ more than one million people attempting to cross the border illegally.",
   o:["apprehends","transcribes","worships","initiates"],src:"4AM/1/10"},
  {s:"Scientists are compiling a global database of all of the world's existing species that will integrate information currently in hundreds of research facilities, libraries and universities.",
   o:["scattered","contradicted","involved","obstructed"],src:"4AM/1/11",noBlank:true},
  {s:"The aardwolf 's ___ legs are longer than its back legs.",
   o:["front","empty","clean","good"],src:"4AM/2/1"},
  {s:"In the past, wine was stored in clay jugs; today, it is usually kept in glass.",
   o:["bottles","corners","gardens","families"],src:"4AM/2/2",noBlank:true},
  {s:"People have ___ musical instruments for over 6,000 years.",
   o:["played","added","opened","erased"],src:"4AM/2/3"},
  {s:"Ballet dancers are the ___ of many paintings by nineteenth-century artist Edgar Degas.",
   o:["subject","property","exchange","assumption"],src:"4AM/2/4"},
  {s:"An ambassador's job is to ___ his or her country's interests abroad.",
   o:["represent","amaze","revise","simplify"],src:"4AM/2/5"},
  {s:"Tokyo is the most crowded city in the world, with over 30 million ___.",
   o:["residents","barriers","rituals","continents"],src:"4AM/2/6"},
  {s:"The ___ worn by the Vatican's Swiss Guard was designed in the early 16th century.",
   o:["uniform","station","shoulder","kettle"],src:"4AM/2/7"},
  {s:"Although Beethoven was deaf, he was able to ___ his handicap and compose the magnificent Ninth Symphony.",
   o:["overcome","undertake","overdo","undergo"],src:"4AM/2/8"},
  {s:"Satellites that were ___ employed to track the movements of the Soviet Army are now being used to monitor changes in the global environment.",
   o:["formerly","relatively","obviously","instantly"],src:"4AM/2/9"},
  {s:"Until he entered the University of Vienna, the Austrian physicist Erwin Schrödinger had been educated at home by a private.",
   o:["tutor","burglar","peddler","janitor"],src:"4AM/2/10",noBlank:true},
  {s:"According to the United States military, nearly 15 percent of all Gulf War ___ suffer from a puzzling medical condition called Gulf War Syndrome.",
   o:["veterans","acquisitions","guarantees","frequencies"],src:"4AM/2/11"},
  {s:"In their youth, the brothers Heinrich and Thomas Mann regarded themselves as brilliant writers who were literary greatness.",
   o:["destined for","enrolled in","liberated from","reproduced by"],src:"4AM/2/12",noBlank:true},
  {s:"Dirty snow melts faster ___ clean snow.",
   o:["than","but","for","since"],src:"4AM/3/1"},
  {s:"Each year, 17 tons of gold are used to make wedding ___ in the United States.",
   o:["rings","skins","plans","lights"],src:"4AM/3/2"},
  {s:"Stamp collecting is no longer as common a ___ as it once was.",
   o:["hobby","jealousy","delivery","factory"],src:"4AM/3/3"},
  {s:"For years, the cigarette industry was aware of the harmful effects of smoking but them to the public.",
   o:["lied about","stood on","reached for","worked with"],src:"4AM/3/4",noBlank:true},
  {s:"Each year, the U.S. Forest Service issues a report predicting the ___ its policies may have on the environment.",
   o:["impact","insight","odor","acclaim"],src:"4AM/3/5"},
  {s:"All university students in nineteenth-century Britain were expected to have at least a basic Greek and Roman literature.",
   o:["familiarity with","establishment of","obedience to","prohibition of"],src:"4AM/3/6",noBlank:true},
  {s:"The Irish mathematician Sir William Hamilton showed an early and astonishing talent for languages: he had thirteen of them by the age of twelve.",
   o:["mastered","reserved","tempted","distracted"],src:"4AM/3/7",noBlank:true},
  {s:"Czar Nicholas I was known for his harsh rule and ___ all political reform.",
   o:["resistance to","restoration of","reflection on","reputation for"],src:"4AM/3/8"},
  {s:"Europeans discovered so many new plant species in the New World between 1550 and 1700 that it became necessary to devise an entirely new system of botanical.",
   o:["classification","justification","industrialization","purification"],src:"4AM/3/9",noBlank:true},
  {s:"Atoms and subatomic particles are so ___ that they can be seen only with the help of very powerful microscopes.",
   o:["minute","persistent","rebellious","uneasy"],src:"4AM/3/10"},
  {s:"Over seventy percent of Canadians live ___ 160 kilometers of the United States border.",
   o:["within","under","before","throughout"],src:"4AM/3/11"},
  {s:"The stomach has the ability to expand or ___, depending on the amount of food it contains.",
   o:["contract","relate","support","define"],src:"4AM/3/12"}],
  rs:[
  {s:"George Washington was the sole planner and architect of his home, Mount Vernon.",
   o:["George Washington designed Mount Vernon by himself.","The only home George Washington ever designed was Mount Vernon.","The architectural plans for George Washington's home were unique.","George Washington hired the best architects to plan his home."],src:"4AM/1/12"},
  {s:"In his book The Kuzari, Yehuda Halevi creates an imaginary dialogue between a king and a sage as a means of setting forth his philosophical beliefs.",
   o:["As a way to present his philosophical ideas, Yehuda Halevi invents a discussion between a king and a sage in his book The Kuzari.","The king and the sage in Yehuda Halevi's The Kuzari hold a philosophical discussion about creativity and the imagination.","In The Kuzari, written by Yehuda Halevi, a sage imagines that he is having a dialogue with a king, to whom he explains his philosophical ideas.","The king in Yehuda Halevi's book The Kuzari sets out on a journey to find a sage who is willing to teach him the basic ideas of philosophy."],src:"4AM/1/13"},
  {s:"Only twelve percent of New Zealand's workforce is employed in agriculture, yet agricultural products are the mainstay of the country's economy.",
   o:["Although farming is vital to the economy of New Zealand, most of the country's workers are not employed in agriculture.","New Zealand's economy has remained stable mainly because only a small fraction of the workforce is involved in agriculture.","Although the country's economy is strong, more than twelve percent of the population of New Zealand has to work in agriculture.","Because of the state of the economy, twelve percent of New Zealand's agricultural workforce is no longer employed."],src:"4AM/1/14"},
  {s:"A number of prominent neuroscientists believe that Freudian ideas persist for one simple reason: science has failed to provide an obviously superior explanation of the psyche.",
   o:["Freud's theories of the mind are still accepted only because science has not been able to offer a more convincing alternative, according to some well-known neuroscientists.","Most neuroscientists disagree with Freud's ideas about the psyche, but they have failed to provide a better explanation of their own.","Though neuroscientists have so far failed to disprove Freudian theories of psychology, they persist in their attempts to do so.","Some prominent neuroscientists continue to believe in Freudian theories because they do not think there is any conflict between Freud's explanations of the psyche and their own."],src:"4AM/1/15"},
  {s:"While acid rain is commonly presumed to be a twentieth-century phenomenon, the term was coined in the nineteenth century to describe the polluted rainfall of Manchester, England.",
   o:["The term \"acid rain\" was first used in the nineteenth century to describe polluted rain; the problem did not begin in the twentieth century, as many people believe.","While acid rain is known to be a twentieth-century phenomenon, polluted rainfall was observed even in the nineteenth century.","The term \"acid rain\" was coined in the nineteenth century, but it was not used to refer to polluted rainfall until the twentieth century.","While acid rain is mistakenly thought to be a twentieth-century phenomenon, it was actually common even in the nineteenth century."],src:"4AM/1/16"},
  {s:"George Herbert's religious poems appeal to readers irrespective of their own beliefs.",
   o:["It is not necessary to share George Herbert's beliefs in order to enjoy his religious poems.","It is clear from the poems of George Herbert that he respected religious beliefs that differed from his own.","George Herbert's poems encourage his readers to explore their own religious beliefs.","The appeal of George Herbert's poems stems from the religious beliefs that they express."],src:"4AM/1/17"},
  {s:"Although Greenland is officially part of Denmark, Danish is not its predominant language.",
   o:["Danish is not the most widely spoken language in Greenland, even though Greenland belongs to Denmark.","Because most people in Greenland speak Danish, it has become the country's official language.","Danish is not the traditional language of Greenland, which only recently became part of Denmark.","Although Greenland is part of Denmark, most of the people there refuse to speak Danish."],src:"4AM/2/13"},
  {s:"Thomas Aquinas wrote: \"There is nothing on this earth more to be prized than true friendship.\"",
   o:["According to Thomas Aquinas, real friendship is the most valuable thing in the world.","True friends, wrote Thomas Aquinas, should be rewarded for their loyalty.","There was nothing in the world that Thomas Aquinas wished for more than a close friend.","As Thomas Aquinas once wrote, true friends are very difficult to find."],src:"4AM/2/14"},
  {s:"Macular degeneration is the leading cause of adult blindness.",
   o:["Adult blindness is most commonly caused by macular degeneration.","Adult blindness sometimes leads to macular degeneration.","Macular degeneration is one form of adult blindness.","Macular degeneration is thought to be a cause of adult blindness."],src:"4AM/2/15"},
  {s:"Crippled by a debt of 34 million dollars, the French railway company intends to eliminate some of the routes that are unprofitable.",
   o:["The French railway company plans to cancel some of its unprofitable routes because of the 34-million-dollar debt it has incurred.","Despite the fact that the French railway company has suspended service on some of its unprofitable routes, its debt has reached 34 million dollars.","Due to the fact that many of its routes are unprofitable, the French railway company is now crippled by a debt of 34 million dollars.","Although it has some unprofitable routes and a 34-million-dollar debt, the French railway company will continue to provide service."],src:"4AM/2/16"},
  {s:"The Roman armies excelled not only at fighting, but also at building walls, forts, roads and aqueducts.",
   o:["Roman soldiers were highly skilled builders of walls, forts, roads and aqueducts as well as outstanding fighters.","Soldiers in the Roman armies were taught not only to fight, but also to build walls, forts, roads and aqueducts.","Some of the best walls, forts, roads and aqueducts ever built were those constructed by the Roman armies.","When the Roman armies were not needed for fighting, they helped to build excellent walls, forts, roads and aqueducts."],src:"4AM/2/17"},
  {s:"In a public debate, a speaker who elects to disparage his opponent rather than refute his arguments may be attempting to disguise the vulnerability of his own position.",
   o:["By insulting his opponent rather than disproving his arguments, a debater may be trying to hide the fact that his own arguments are weak.","If a candidate in an election refuses to meet with his opponent and debate him face to face, people may think that he is unsure of his own opinions.","Unfortunately, it is common for debaters to ridicule their opponents' views rather than present reasonable and polite arguments.","In a public debate, a speaker may try to show the weakness of his opponent's arguments by disparaging them rather than by refuting them."],src:"4AM/2/18"},
  {s:"Timber exports were the cornerstone of the Gabonese economy until the 1970s, when substantial offshore oil deposits were discovered; nonetheless, logging remains the country's second largest generator of revenue.",
   o:["Today, logging is Gabon's second biggest industry, having been replaced by oil as the country's main source of income in the 1970s.","Although oil generates a large amount of income for Gabon, timber accounts for most of the country's revenue, and has done so since the 1970s.","Since the 1970s, Gabon has exported huge amounts of timber, making logging the country's second largest source of revenue after oil.","Because Gabon's economy is now dependent on oil exports, the logging industry, which thrived until the 1970s, has declined dramatically in recent years."],src:"4AM/2/19"},
  {s:"When Italian composer Puccini died, his last opera was left incomplete.",
   o:["Puccini died before he could finish his last opera.","Puccini completed his last opera a short time before he died.","Puccini knew he was dying as he wrote his last opera.","Puccini's last opera was found several years after his death."],src:"4AM/3/13"},
  {s:"Thomas Jefferson once said: \"I find that the harder I work, the more luck I seem to have.\"",
   o:["Thomas Jefferson believed that good luck is the result of hard work.","Thomas Jefferson enjoyed life despite the fact that he had to work hard.","Thomas Jefferson worked hard for his success, but many thought he was just lucky.","Thomas Jefferson lived in hard times and was always glad to find work."],src:"4AM/3/14"},
  {s:"American artist James Whistler spent his student days in Paris.",
   o:["James Whistler lived in Paris when he was a student.","James Whistler felt that every art student should spend time in Paris.","James Whistler always wished that he had studied art in Paris.","As a student, James Whistler often traveled to Paris."],src:"4AM/3/15"},
  {s:"Although Pablo Picasso is best known for his paintings, he also produced sculptures, drawings, ceramics and prints.",
   o:["Pablo Picasso created sculptures, drawings, prints and ceramics in addition to paintings, for which he is most famous.","Before he became famous as a painter, Pablo Picasso produced many sculptures, drawings, ceramics and prints.","Many of Pablo Picasso's best-known paintings are similar to other works that he produced, such as sculptures, drawings, ceramics and prints.","Although Pablo Picasso tried sculpting, drawing, ceramics and printmaking, he was most successful at painting."],src:"4AM/3/16"},
  {s:"William Shakespeare based the plot of The Winter's Tale largely on Robert Greene's Pandosto: The Triumph of Time.",
   o:["Much of the plot of The Winter's Tale, by William Shakespeare, was taken from Robert Greene's Pandosto: The Triumph of Time.","Robert Greene took some of the ideas for Pandosto: The Triumph of Time from William Shakespeare's The Winter's Tale.","The Winter's Tale by William Shakespeare and Pandosto: The Triumph of Time by Robert Greene have very similar plots.","William Shakespeare's The Winter's Tale and Robert Greene's Pandosto: The Triumph of Time are based on the same source."],src:"4AM/3/17"},
  {s:"Legally sanctioned adoption dates from ancient Greece and Rome, where it served the function of preserving intact the estates of citizens who otherwise would have had no male heir.",
   o:["Legal adoptions began in ancient Greece and Rome to make it possible for a person without sons to pass on his estate in its entirety.","Adoption first became a common practice in ancient Greece and Rome, although it was legal only for male citizens who had estates.","In Greek and Roman times it was common for families who had no male heir to adopt one, though the practice was not legally recognized.","In ancient Greece and Rome, even before the practice of adoption became legal, any male citizen could serve the function of an heir."],src:"4AM/3/18"},
  {s:"The giant panda is capable of making eleven distinct and complex vocalizations, allowing it to communicate subtle variations in attitude and mood.",
   o:["The giant panda can express a range of feelings by using eleven different sounds.","Although they are capable of making only eleven vocalizations, giant pandas have other means of communicating their attitudes and moods.","It is believed that the eleven distinct vocalizations made by giant pandas are attempts to communicate attitudes and moods.","By combining eleven simple sounds, the giant panda can express complex emotions."],src:"4AM/3/19"}]},
 "5AM":{verified:false,
  sc:[
  {s:"The town of Beaumont, Texas, recently celebrated the 100th ___ of the discovery of oil there.",
   o:["anniversary","diversity","abbreviation","donation"],src:"5AM/1/1"},
  {s:"Dieticians recommend that growing children be given daily ___ of vitamins and minerals.",
   o:["doses","alarms","handles","coughs"],src:"5AM/1/2"},
  {s:"Unfortunately, the problem of homelessness has ___ in many countries over the past decade.",
   o:["worsened","floated","failed","softened"],src:"5AM/1/3"},
  {s:"During World War I, French military forces trained parrots to ___ troops of approaching enemy aircraft.",
   o:["alert","reclaim","invest","enforce"],src:"5AM/1/4"},
  {s:"The World Wildlife Fund supports research on endangered animal species and other projects.",
   o:["conservation","contemplation","confrontation","congestion"],src:"5AM/1/5",noBlank:true},
  {s:"Headdresses made from exotic bird feathers were a symbol of high social status among Incan.",
   o:["nobles","excuses","captives","grains"],src:"5AM/1/6",noBlank:true},
  {s:"It is essential to find substitute sources of energy because the amount of fossil fuel on earth is.",
   o:["finite","comparable","vital","prominent"],src:"5AM/1/7",noBlank:true},
  {s:"The city of Abidjan was the capital of the Ivory Coast until 1983, when Yamoussoukro was as the new capital.",
   o:["designated","illuminated","duplicated","intimidated"],src:"5AM/1/8",noBlank:true},
  {s:"After the Second World War, Western European nations cooperated closely to ___ that there would be no revival of Germany's military might.",
   o:["ensure","pretend","hesitate","recollect"],src:"5AM/2/1"},
  {s:"The loss of any one sense, such as sight or hearing, changes the way a person ___ the world.",
   o:["perceives","ignores","resists","accuses"],src:"5AM/2/2"},
  {s:"In 2001, China exported 102 billion dollars' worth of ___ – ranging from shoes to electronics – to the United States.",
   o:["goods","clues","wounds","yawns"],src:"5AM/2/3"},
  {s:"German physicist Gabriel Fahrenheit created an improved, more ___ thermometer by filling it with mercury instead of alcohol.",
   o:["accurate","conscious","tense","foreign"],src:"5AM/2/4"},
  {s:"While investigating another crime, the police ___ a plot to steal the Mona Lisa.",
   o:["uncovered","decreased","replaced","enclosed"],src:"5AM/2/5"},
  {s:"Medieval manuscripts of Geoffrey Chaucer's Canterbury Tales contain different versions of the work because each scribe made his own as he copied the text.",
   o:["alterations","adversaries","alliances","acquittals"],src:"5AM/2/6",noBlank:true},
  {s:"Plants of the valerian family grow ___ in the Northern Hemisphere, but some are found in the Southern Hemisphere.",
   o:["chiefly","silently","pitifully","gently"],src:"5AM/2/7"},
  {s:"On November 6, 1984, General Pinochet seized all political power in Chile, abruptly the process of political liberalization that had begun fifteen months earlier.",
   o:["halting","installing","generating","summarizing"],src:"5AM/2/8",noBlank:true}],
  rs:[
  {s:"No star, apart from the sun, is close enough to earth to appear as anything but a tiny point of light.",
   o:["All stars – except for the sun – look like very small points of light because they are so far from earth.","Anything that is far away from the sun or earth and looks like a tiny point of light is a star.","Compared to the sun, other stars can provide earth with only a tiny amount of light.","The smallest points of light that can be seen from earth come from stars that are more distant than the sun."],src:"5AM/1/9"},
  {s:"Chekhov called his play The Seagull a comedy, a description which has always puzzled playgoers, actors, directors and critics.",
   o:["People have always wondered why Chekhov described The Seagull as a comedy.","Chekhov did not know how to describe his play The Seagull, although many viewed it as a comedy.","For many people, one of the most puzzling of Chekhov's comedies has always been The Seagull.","Despite Chekhov's opinion of his play, those who have seen The Seagull agree that it is a comedy."],src:"5AM/1/10"},
  {s:"H. G. Wells' literary output extended well beyond the science fiction for which he is renowned and included theater reviews and scientific essays.",
   o:["Although he is best known for his science fiction, H. G. Wells also wrote theater reviews and scientific essays, among other types of works.","While H. G. Wells is renowned as an author of science fiction, he preferred his other works, particularly theater reviews and scientific essays.","H. G. Wells' science fiction works are his most popular, but his other works – which include theater reviews and scientific essays – are of a higher standard.","H. G. Wells spent the early part of his career writing science fiction, but his later literary output consisted of theater reviews and scientific essays."],src:"5AM/1/11"},
  {s:"Venetian artist Tintoretto was dubbed \"Il Furioso\" because of the frenetic pace at which he painted.",
   o:["Tintoretto's nickname, \"Il Furioso,\" alludes to his intense speed as a painter.","Tintoretto admired Il Furioso because of the emotional depth of his paintings.","Tintoretto, the eccentric Venetian painter, signed his works \"Il Furioso.\"","Tintoretto's painting expressed his existential rage, earning him the label \"Il Furioso.\""],src:"5AM/1/12"},
  {s:"Today, nearly all trains are powered by electricity or diesel fuel rather than steam.",
   o:["Most trains today are powered by electricity or diesel fuel, not steam.","Most electric and diesel train engines can also be powered by steam.","Steam trains are less powerful than those that use electricity or diesel fuel.","Today, most trains are powered by electricity, diesel fuel, or steam."],src:"5AM/2/9"},
  {s:"The coqui, a small tree frog that lives on the island of Puerto Rico, is rarely found anywhere else in the world.",
   o:["Puerto Rico is practically the only place in the world where the coqui lives.","The coqui, the world's rarest tree frog, lives on the island of Puerto Rico.","People come to Puerto Rico from all over the world to see the coqui, a small tree frog.","Several animals, including the coqui, are found only in Puerto Rico."],src:"5AM/2/10"},
  {s:"Although it shared the fundamental features of previous economic depressions, the Great Depression of the 1930s was unprecedented in its length and in the wholesale poverty and tragedy it inflicted on society.",
   o:["The Great Depression of the 1930s was similar to earlier economic depressions, but it lasted longer and caused more extensive poverty and suffering than any depression before it.","Although the Great Depression of the 1930s did not last as long as other economic depressions, it inflicted more poverty and tragedy on society than any other depression in history.","The Great Depression of the 1930s was different from every other economic depression in that it not only impoverished many people, but it also brought tragedy to society as a whole.","Because the Great Depression of the 1930s caused so much poverty and suffering, its effects on society lasted longer than those of any depression since."],src:"5AM/2/11"},
  {s:"American patriot Samuel Adams skillfully exploited the 1770 Boston Massacre – in which eight British soldiers shot and killed several demonstrators – to foment anti-British sentiment in the colonies.",
   o:["Samuel Adams expertly manipulated the Boston Massacre to incite resentment towards the British in the American colonies.","The Boston Massacre was the turning point in Samuel Adams' campaign against British rule in the American colonies.","Prior to the Boston Massacre, few people opposed the British presence in the American colonies, with the exception of Samuel Adams.","Samuel Adams was able to exploit anti-British sentiment in the colonies to persuade many Americans that the British were responsible for the Boston Massacre."],src:"5AM/2/12"}]}
};
